version: '3'

services:
  pk_generator:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: 995762937/pk_generator
    container_name: pk_generator
    environment:
      TZ: Asia/Shanghai
#      CHATGPT_PROXY: ""
      UNIQUE_NAME: "my share token"
      POOL_TOKEN: ""
      ONLY_PK: True
      ONLY_FK: False
    volumes:
      - ./file:/home/file
    network_mode: "host"
